version: '3.9'
services:
  mysql:
    image: mysql:latest
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password