name = "ai-call"
main = "src/index.ts"
compatibility_date = "2024-12-31"

compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ai-call_dev"
database_id = "b0d0f706-dee9-4cfb-8bde-2f1daa8910d2"
