name: Lint and Format Check

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Install Reviewdog
        working-directory: ./backend
        uses: reviewdog/action-setup@v1

      - name: Run ESLint with Reviewdog
        working-directory: ./backend
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lint -s -- -f json | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true

      - name: Run Prettier Check with Reviewdog
        working-directory: ./backend
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run format:check -s > prettier.log || true
          cat prettier.log | reviewdog -efm="%f" -name="prettier" -reporter=github-pr-review -level=warning

  type-check:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Run Type Check
        working-directory: ./backend
        run: npm run type-check || true

      - name: Report TypeScript errors
        working-directory: ./backend
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run type-check -s -- --pretty false | reviewdog -efm="%f(%l,%c): %m" -name="typescript" -reporter=github-pr-review -level=error
