name: Lint and Format Check

on:
  pull_request:

defaults:
  run:
    working-directory: backend

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: step
        run: |
          pwd

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run ESLint with Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lint -s -- -f json | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true

      - name: Run Prettier Check with Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run format:check -s > prettier.log || true
          cat prettier.log | reviewdog -efm="%f" -name="prettier" -reporter=github-pr-review -level=warning

  type-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Type Check
        run: npm run type-check || true

      - name: Report TypeScript errors
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run type-check -s -- --pretty false | reviewdog -efm="%f(%l,%c): %m" -name="typescript" -reporter=github-pr-review -level=error
